### ISSUE TITLE
Consider reporting Rustual Boy version instead of frontend version

### ISSUE THREAD

**Issue by sebbert** [sebbert/rustual-boy-libretro#1]
This would require rustual-boy to export its version: 
```
pub const VERSION: &'static str = env!("CARGO_PKG_VERSION");
```

**Comment by yupferris** [comment]
Good call on this; once the libretro frontend is functioning and ready to go into upstream we'll make this a ticket on the emu repo :)

**Comment by yupferris** [comment]
After thinking more about this I actually think we should instead still report the frontend version, and try to keep that updated as part of the release process.
