### ISSUE TITLE
Maybe get rid of stdlib at some point

### ISSUE THREAD

**Issue by sebbert** [sebbert/rustual-boy-libretro#3]
> yupferris - Today at 12:12 AM
> because another thing we may face pretty soon here is removing the std dependency from the core
> we may not have to, but I believe certain platforms like android or 3ds would have problems with std

**Comment by yupferris** [comment]
Note that this may not be necessary, but good to have documented so we keep it in mind :)

**Comment by yupferris** [comment]
Closing this as keeping track of it isn't super important atm
