### ISSUE TITLE
Figure out serialization/deserialization

### ISSUE THREAD

**Issue by sebbert** [sebbert/rustual-boy-libretro#4]
[SerDe](https://github.com/serde-rs/serde) seems excellent, especially with the new custom derive feature in rustc, allowing for [automatic implementations of Serialize/Deserialize](https://serde.rs/codegen.html).

The main thing to consider is the format. [MessagePack](https://github.com/3Hren/msgpack-rust) and [Bincode](https://github.com/TyOverby/bincode) both seem appropriate here, but this needs some investigation. Luckily SerDe is format-agnostic :)

**Comment by yupferris** [comment]
Another thing is going to be performance. I doubt these operations will be terribly expensive, but we'll want to test that out before this gets used in some per-frame stuff for rewinding, etc :)

**Comment by yupferris** [comment]
Migrated to https://github.com/emu-rs/rustual-boy/issues/36
