### ISSUE TITLE
Use libretro for logging

### ISSUE THREAD

**Issue by sebbert** [sebbert/rustual-boy-libretro#6]
Currently, log output is done through stderr. Libretro has a [logging interface](https://github.com/libretro/libretro-common/blob/master/include/libretro.h#L1277-L1294) we should use instead. See [here](https://github.com/simias/rustation-libretro/blob/master/src/libretro.rs#L443-L450) for how to deal with the fact that libretro's logging function is variadic.

**Comment by yupferris** [comment]
Currently there's no more logging in the core, so this doesn't really apply
