### ISSUE TITLE
Bad pixel format on Windows

### ISSUE THREAD

**Issue by yupferris** [sebbert/rustual-boy-libretro#9]
Seen this mentioned a couple times, and saw it once or twice myself. :)

**Comment by sebbert** [comment]
Yes, seems to be the windows build of retroarch not wanting to set the pixel format to XRGB8888 (haven't checked with other formats). This only happens _sometimes_ though. Need to investigate wether this is a bug in retroarch, or if there's something I've missed in the docs.

Nevertheless, I eventually want to support all pixel formats that are supported by libretro.

**Comment by yupferris** [comment]
Migrated to https://github.com/emu-rs/rustual-boy/issues/36
